# Generated by Django 3.2.22 on 2023-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_adi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(max_length=200)),
            ],
        ),
    ]
