# Generated by Django 3.2.22 on 2023-11-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0002_site_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='about_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya Video Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='alkol_baslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='alkoller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
                ('baner_resim', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
                ('baner_resim', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
                ('İD_numrası', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='galeri_baslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ürünler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.CharField(max_length=400)),
                ('baner_resim', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
        migrations.DeleteModel(
            name='email_adres',
        ),
        migrations.DeleteModel(
            name='sosyalmedyalinkd',
        ),
        migrations.DeleteModel(
            name='sosyalmedyaTw',
        ),
        migrations.AddField(
            model_name='banner',
            name='aciklama',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='baslik',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='baner_resim',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz'),
        ),
    ]
