# Generated by Django 3.2.22 on 2023-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0005_auto_20231105_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ürünler',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Ürünler Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
    ]
