# Generated by Django 3.2.22 on 2023-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0006_alter_ürünler_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Hakkımızda Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='alkol_baslik',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Alkoller Başlık Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='alkoller',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Alkoller Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Banner Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='galeri',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Galeri Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='galeri_baslik',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Baleri Başlık Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
    ]
