# Generated by Django 3.2.22 on 2023-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0010_auto_20231105_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numara',
            name='sirket_numarasi',
            field=models.CharField(max_length=11),
        ),
    ]
