# Generated by Django 3.2.22 on 2023-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0011_alter_numara_sirket_numarasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='baslik',
            new_name='baslik1',
        ),
        migrations.AddField(
            model_name='banner',
            name='baslik2',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
