# Generated by Django 3.2.22 on 2023-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0012_auto_20231105_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alkol_baslik',
            old_name='baslik',
            new_name='baslik1',
        ),
        migrations.AddField(
            model_name='alkol_baslik',
            name='baslik2',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
