# Generated by Django 3.2.22 on 2023-11-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0013_auto_20231105_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='baslik',
            new_name='baslik1',
        ),
        migrations.RenameField(
            model_name='alkol_baslik',
            old_name='baslik1',
            new_name='baslik',
        ),
        migrations.RemoveField(
            model_name='alkol_baslik',
            name='baslik2',
        ),
        migrations.AddField(
            model_name='about',
            name='baslik2',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
