# Generated by Django 3.2.22 on 2023-11-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0014_auto_20231105_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='about_video',
        ),
        migrations.DeleteModel(
            name='adres',
        ),
        migrations.DeleteModel(
            name='alkol_baslik',
        ),
        migrations.DeleteModel(
            name='alkoller',
        ),
        migrations.DeleteModel(
            name='banner',
        ),
        migrations.DeleteModel(
            name='galeri',
        ),
        migrations.DeleteModel(
            name='galeri_baslik',
        ),
        migrations.DeleteModel(
            name='konum_link',
        ),
        migrations.DeleteModel(
            name='numara',
        ),
        migrations.DeleteModel(
            name='sayfa_logosu',
        ),
        migrations.DeleteModel(
            name='site_adi',
        ),
        migrations.DeleteModel(
            name='sosyalmedyafb',
        ),
        migrations.DeleteModel(
            name='sosyalmedyaInsgr',
        ),
        migrations.DeleteModel(
            name='whatshappno',
        ),
        migrations.DeleteModel(
            name='ürünler',
        ),
    ]
