# Generated by Django 3.2.22 on 2023-11-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_set', '0015_auto_20231108_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik1', models.CharField(max_length=400)),
                ('baslik2', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Hakkımızda Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya Video Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AlkolBaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Alkoller Başlık Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adlandir', models.CharField(blank=True, help_text='Lütfen Bir İsim Verin', max_length=100, null=True, verbose_name='Görseli Adlandır')),
                ('resim', models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriBaslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Galeri Başlık Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='KonumLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalMedyaFb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalMedyaInsgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Ürünler Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
                ('resim', models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Loğo Ekleme')),
            ],
        ),
        migrations.CreateModel(
            name='SayfaLogosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Loğo Ekleme')),
            ],
        ),
        migrations.CreateModel(
            name='DukkanResmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Galeri Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
                ('ID_numarasi', models.BigIntegerField(null=True)),
                ('resim', models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Loğo Ekleme')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_sirasi', models.BigIntegerField(null=True)),
                ('resim', models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='Alkoller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=400)),
                ('aciklama', models.TextField(blank=True, help_text='Alkoller Açıklama', max_length=400, null=True, verbose_name='Açıklama')),
                ('resim', models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Loğo Ekleme')),
            ],
        ),
    ]
