# Generated by Django 3.2.22 on 2023-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0016_about_aboutvideo_adres_alkolbaslik_alkoller_banner_dukkanresmi_galeri_galeribaslik_konumlink_phonenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='video',
            field=models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Banner'),
        ),
    ]
