# Generated by Django 3.2.22 on 2023-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0017_alter_aboutvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz'),
        ),
    ]
