# Generated by Django 3.2.22 on 2023-11-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0020_kart'),
    ]

    operations = [
        migrations.AddField(
            model_name='kart',
            name='baslik',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kart',
            name='resim',
            field=models.ForeignKey(blank=True, help_text='Logonuzu Seçiniz', null=True, on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Loğo Ekleme'),
        ),
    ]
