# Generated by Django 3.2.22 on 2023-11-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0021_auto_20231112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='resim',
            field=models.ForeignKey(default=1, help_text='Resminizi Seçiniz', on_delete=django.db.models.deletion.CASCADE, to='site_set.galeri', verbose_name='Banner'),
            preserve_default=False,
        ),
    ]
