# Generated by Django 3.2.22 on 2023-11-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0022_alter_banner_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Hakkımızda Açıklama', max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='banner',
            name='baslik1',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='baslik2',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='urunler_link',
            field=models.ForeignKey(default=1, help_text='Ürün Linki', on_delete=django.db.models.deletion.CASCADE, to='site_set.urunler', verbose_name='Ürünü Seçin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kart',
            name='sayfa_sirasi',
            field=models.BigIntegerField(null=True),
        ),
    ]
