# Generated by Django 3.2.22 on 2023-11-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0025_auto_20231112_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Whatsapp_Numara',
            field=models.ForeignKey(help_text='Whatsapp Numarası Seç', on_delete=django.db.models.deletion.CASCADE, to='site_set.whatsappnumber', verbose_name='Whatsapp Numarası'),
        ),
    ]
