# Generated by Django 3.2.22 on 2023-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0027_auto_20231116_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunler',
            old_name='aciklama',
            new_name='açıklama',
        ),
        migrations.RenameField(
            model_name='urunler',
            old_name='baslik',
            new_name='kategori',
        ),
        migrations.AddField(
            model_name='urunler',
            name='marka',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
