# Generated by Django 3.2.22 on 2023-11-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0030_urunler_page_başlık2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunler_page',
            old_name='açıklama',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='urunler_page',
            old_name='başlık',
            new_name='başlik',
        ),
        migrations.RenameField(
            model_name='urunler_page',
            old_name='başlık2',
            new_name='başlik2',
        ),
    ]
