# Generated by Django 3.2.22 on 2023-11-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0034_alter_kart_kartlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Telefon No', 'verbose_name_plural': 'Telefon No'},
        ),
    ]
