# Generated by Django 3.2.22 on 2023-11-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0035_alter_phonenumber_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SosyalMedyaFb',
        ),
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Açık Adres Yaz', 'verbose_name_plural': 'Adres Gir'},
        ),
        migrations.AlterModelOptions(
            name='galeri',
            options={'verbose_name': 'Galeri Resim Ekleme', 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='konumlink',
            options={'verbose_name': 'Konum Linki Gir', 'verbose_name_plural': 'Konum Link'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Telefon Numarası', 'verbose_name_plural': 'Telefon No'},
        ),
        migrations.AlterModelOptions(
            name='sosyalmedyainsgr',
            options={'verbose_name': 'Instagram Link Gir', 'verbose_name_plural': 'Instagram'},
        ),
        migrations.AlterModelOptions(
            name='whatsappnumber',
            options={'verbose_name': 'WhatsApp Numarası', 'verbose_name_plural': 'WhatsApp No'},
        ),
    ]
