# Generated by Django 3.2.22 on 2023-11-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0036_auto_20231117_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAdi',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Slide Banner Bölümü', 'verbose_name_plural': 'Slide'},
        ),
        migrations.AlterModelOptions(
            name='urunler',
            options={'verbose_name': 'Ürün Ekleme', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='urunler_page',
            options={'verbose_name': 'Ürünler Sayfa Başlık', 'verbose_name_plural': 'Ürünler Sayfa'},
        ),
    ]
