# Generated by Django 3.2.22 on 2023-11-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0037_auto_20231117_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlkolBaslik',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Hakkımızda Sayfa', 'verbose_name_plural': 'Hakımızda Bölümü'},
        ),
        migrations.AlterModelOptions(
            name='aboutvideo',
            options={'verbose_name': 'Hakkımızda Video', 'verbose_name_plural': 'Hakkımızda Video'},
        ),
    ]
