# Generated by Django 3.2.22 on 2023-11-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0038_auto_20231117_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alkoller',
            options={'verbose_name': 'Alkoller Anasayfa', 'verbose_name_plural': 'Alkoller Anasayfa'},
        ),
        migrations.AlterModelOptions(
            name='galeribaslik',
            options={'verbose_name': 'Galeri Başlık', 'verbose_name_plural': 'Galeri Başlık'},
        ),
    ]
