# Generated by Django 3.2.22 on 2023-11-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0039_auto_20231117_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dukkanresmi',
            options={'verbose_name': 'Dükkan Resmi Anasayfa', 'verbose_name_plural': 'Dükkan Resmi'},
        ),
        migrations.AlterModelOptions(
            name='kart',
            options={'verbose_name': 'Anasayfa Kart', 'verbose_name_plural': 'Kart Anasayfa'},
        ),
        migrations.DeleteModel(
            name='SayfaLogosu',
        ),
    ]
