# Generated by Django 3.2.22 on 2023-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0040_auto_20231117_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='video',
            field=models.FileField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dukkanresmi',
            name='baslik',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
