# Generated by Django 3.2.22 on 2023-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0041_auto_20231119_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutvideo',
            name='video',
            field=models.FileField(upload_to='banner/%y'),
        ),
    ]
