# Generated by Django 3.2.22 on 2023-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0042_alter_aboutvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='video ekeleme', null=True, upload_to='banner/%y', verbose_name='video ekle')),
                ('etiket', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Hakkımızda Video',
                'verbose_name_plural': 'Hakkımızda Video',
            },
        ),
        migrations.DeleteModel(
            name='AboutVideo',
        ),
    ]
