# Generated by Django 3.2.22 on 2023-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0043_auto_20231119_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_video',
            name='baslık',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about_video',
            name='video',
            field=models.FileField(blank=True, help_text='video ekeleme', null=True, upload_to='banner/', verbose_name='video ekle'),
        ),
    ]
