# Generated by Django 3.2.22 on 2023-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0044_auto_20231119_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='id_numara',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='about_video',
            name='baslık',
            field=models.CharField(blank=True, help_text='video için bir isim ver ', max_length=400, null=True, verbose_name='Adlandır'),
        ),
    ]
